services:
  eshopdb:
    build:
      context: .
      dockerfile: Dockerfile.db

  eshopapi:
    build:
      context: ./Bootstrapper/Api
      dockerfile: Dockerfile
    
volumes:
  postgres_eshopdb: 
