services:
  eshopdb:
    build:
      context: .
      dockerfile: Dockerfile.db

  distributedcache:
    image: redis:8.0

  seq:
    image: datalust/seq:2025.2
  
  messagebus:
    image: rabbitmq:4.3-management

  identity:
    image: quay.io/keycloak/keycloak:26.6.1

volumes:
  postgres_eshopdb: 
